language: php

php:
  - "5.4"
  - "5.3"

notifications:
  irc: "irc.freenode.net#orchestra-platform"

before_install:
  - cd ../../
  - git clone git://github.com/laravel/laravel.git
  - mv ./orchestral/authorize ./laravel/bundles/authorize
  - cd ./laravel
  - php artisan bundle:install orchestra
  - echo "<?php return array('orchestra' => array('auto' => true, 'handles' => 'orchestra'), 'authorize');" > ./application/bundles.php

script: "php artisan test authorize"
